myModules/users/manifests/init.pp

I added my public ssh key to the users list for puppet.

Added ssh_authorized_key for Mario (mari9064)

---

Puppetfile
myModules/basic_workstation/manifests/dev_tools.pp

Update versions so that new capabilities can be leveraged

Update forge modules

---

Puppetfile
myModules/adrian_workstation/manifests/init.pp
myModules/basic_workstation/manifests/dev_tools.pp
myModules/basic_workstation/manifests/personal_networking.pp
myModules/repose_gradle/manifests/init.pp
myModules/repose_groovy/manifests/init.pp
myModules/repose_idea/manifests/init.pp

Personal manifest

---

myModules/repose_jenkins/manifests/init.pp

Just a little added assurance and clarity around the docker0 bridge.

REP-4873 Static docker0 bridge IP

---

myModules/basic_workstation/files/clusters_config
myModules/basic_workstation/files/ssh_config
myModules/basic_workstation/manifests/hosts.pp

Updates to reflect the removal of performance.openrepose.org box

Removal of performance.openrepose.org

---

myModules/repose_jenkins/manifests/master.pp

This PR won't actually do anything until this story is fixed:
https://repose.atlassian.net/browse/REP-4597
But I'm updating the Jenkins plugin versions to match the actual versions to make it easier to work that story when it does come up.
If you want to see which Jenkins plugins are installed:
https://jenkins.openrepose.org/pluginManager/installed
If you want a table comparing this PR and the Jenkins plugin versions:
https://repose.atlassian.net/browse/REP-4597?focusedCommentId=32204&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-32204
Code review task:
https://repose.atlassian.net/browse/REP-5450

REP-3191 Update Jenkins plugins

---

Puppetfile
manifests/site.pp
myModules/repose_grafana/manifests/init.pp
myModules/repose_grafana/metadata.json
myModules/repose_grafana/restore.adoc

Builds it from scratch with backups. I've also included restore directions.

REP-5335 Grafana

---

README.md
manifests/site.pp
myModules/repose_nagios/files/nagios_config/host_grafana.cfg
myModules/repose_nagios/files/nagios_config/host_influxdb.cfg
myModules/repose_nagios/files/nagios_config/host_phone-home.cfg
myModules/repose_nagios/files/nagios_config/hostgroups.cfg

Also a little bit of cleanup of other things.

REP-5468 Added nagios monitoring to a couple of boxes 

---

manifests/site.pp
myModules/repose_jenkins/manifests/init.pp
myModules/repose_jenkins/manifests/legacy_slave.pp
myModules/repose_jenkins/manifests/modern_slave.pp
myModules/repose_jenkins/manifests/slave.pp

Wait to do this one till after #58

REP-4596 Now with legacy slave manifest

---

myModules/repose_grafana/restore.adoc
myModules/repose_influxdb/files/influxdb-backup-compress.sh
myModules/repose_influxdb/manifests/init.pp
myModules/repose_influxdb/restore.adoc

Also made the cleanup run daily deleting backups older than 30 days.

REP-5855 InfluxDB disk space issue

---

myModules/repose_grafana/manifests/init.pp

No big changes.
https://community.grafana.com/t/release-notes-for-grafana-v4-4-x/1650/3

Upgrading Grafana version from 4.4.1 to 4.4.2

---

myModules/repose_grafana/manifests/init.pp

No big changes.
https://community.grafana.com/t/release-notes-for-grafana-v4-4-x/1650/4

Upgrading Grafana version from 4.4.2 to 4.4.3

---

myModules/repose_gradle/manifests/init.pp
myModules/repose_jenkins/manifests/master.pp
myModules/repose_sonar/manifests/init.pp
myModules/repose_sonar/metadata.json

Upgraded Gradle and installed the Scoverage plugin for Sonar.

REP-5765 Adding Support for Scoverage

---

myModules/repose_grafana/manifests/init.pp

Ruh-roh. While testing this, it appears that the upgrade killed communication with InfluxDB. Looking into it...

REP-6190 Bumping Grafana to the latest version

---

myModules/repose_influxdb/manifests/init.pp

This PR requires the companion framework PR at:
https://github.com/rackerlabs/repose/pull/1924

REP-6882 (REP-5334) Collect JMX Metrics for Performance Tests

---

myModules/repose_grafana/manifests/init.pp

There were minor bug fixes that should not effect us in any way:
> https://github.com/grafana/grafana/blob/master/CHANGELOG.md#512-2018-05-09

Updated Grafana from v5.1.1 to v5.1.2.

---

myModules/repose_grafana/manifests/init.pp

Release notes:
https://community.grafana.com/t/release-notes-v5-2-x/7894

REP-7181 Upgraded Grafana from v5.2.1 to v5.2.2

---

myModules/repose_grafana/manifests/init.pp

See: [Grafana 5.2.3 and 4.6.4 Security Update](https://community.grafana.com/t/grafana-5-2-3-and-4-6-4-security-update/10050)

Upgraded Grafana from v5.2.2 to v5.2.3.

---

myModules/repose_grafana/manifests/init.pp

 Upgraded Grafana from v5.3.0 to v5.3.1

---

myModules/repose_nagios/files/client_nrpe.conf

to account for the possiblity of jvm arguements

Updated jenkins agent check

---

myModules/repose_jenkins/manifests/master.pp

REP-7614 Upgrading Jenkins' plugins

---

myModules/users/manifests/init.pp

Once this gets merged, we will need to update the rebase REP-7611_UpgradeNagiosPhoneHome for the changes to take effect.

Removing OBE'd SSH keys
