myModules/users/manifests/init.pp

Ensures my key, and @tylerroyal 's key are absent.
Manual work is required to remove our users from Jenkins and Mumble. Also the github orgs.
Also from JIRA.

DROP THE TRAITOR and the manager guy

---

Puppetfile
myModules/repose_jenkins/manifests/init.pp

GCC is not installed by default on the new Ubuntu boxes and is now required by the API-Checker test suite which is now using Nailgun.

REP-4496 Install gcc on Jenkins boxes

---

myModules/repose_jenkins/manifests/init.pp

Turns out, the "github.com" ssh key entry is already present in the global ssh_known_hosts file. Our base module puts it there. Thus, I suspect that the Gradle plugin cloning the Git repository only uses the user's known hosts for some reason.
Anyway, it appears that Puppet has a built-in resource to handle this case – sshkey. Unfortunately, Puppet won't let you define multiple resources with the same title or alias. Pretty annoying when you want to set up the same key for multiple users. That's why I appended "-for-jenkins" to a couple of things.
Feel free to tell me that this is garbage.

REP-4874 Update Repose infrastructure to fix publishing docs during Repose release builds

---

manifests/site.pp
myModules/repose_jenkins/manifests/init.pp

So I tried setting the docker0 bridge to a static address, but did not succeed. All the things I tried ended up breaking Docker or the Docker Puppet module in some way. I'll probably keep poking at this trying to figure it out.
With that said, I believe that the default settings Docker uses are static, and will only change if:
- Docker updates and changes the default settings or behavior
- The IP Docker tries to use by default is already in use
As a result, what I have right now is working. It just sets the firewall settings to work with the default docker0 bridge.

REP-4873 Adding Docker networking to firewall

---

myModules/backup_cloud_files/files/pyraxbackend.py
myModules/backup_cloud_files/manifests/init.pp
myModules/backup_cloud_files/templates/duplicity_script.rb.erb

It appears that some of the whitespace in the original backend file may not have been of the correct `charset` and new versions seemed to care.

REP-5168 fix sonar backups

---

myModules/adrian_workstation/metadata.json
myModules/backup_cloud_files/metadata.json
myModules/base/metadata.json
myModules/basic_workstation/metadata.json
myModules/cloud_monitoring/metadata.json
myModules/joel_workstation/metadata.json
myModules/mumble_server/metadata.json
myModules/puppet_master/metadata.json
myModules/repose_gradle/metadata.json
myModules/repose_groovy/metadata.json
myModules/repose_idea/metadata.json
myModules/repose_influxdb/metadata.json
myModules/repose_jenkins/metadata.json
myModules/repose_maven/metadata.json
myModules/repose_nagios/metadata.json
myModules/repose_nexus/metadata.json
myModules/repose_phone_home/metadata.json
myModules/repose_redirects/metadata.json
myModules/repose_sonar/metadata.json
myModules/ssl_cert/metadata.json
myModules/users/metadata.json

They were missing some required fields. Without those fields, the modules were not working.
From the Puppet docs:
> You also have the option of writing classes and defined types by hand and placing them in properly named manifest files as described in the “Module Layout” section above. If you take this route, you must ensure that your metadata.json file is properly formatted or your module will not work.

Fixing metadata.json files

---

myModules/repose_jenkins/manifests/performance_slave.pp

I did not fully qualify `ansible-galaxy` or provide a path. That's a requirement.

REP-4020 Fixing the ansible-galaxy command

---

myModules/repose_grafana/manifests/init.pp
myModules/repose_influxdb/manifests/init.pp
myModules/repose_sonar/manifests/database.pp

I will note that I do not update the `mumble_server` manifest for two reasons:
1. It will no longer be in use soon (and may be deleted?).
1. The Duplicity script path is hard-coded in a Ruby file (which, in addition to calling the Duplicity script also backs up the database) rather than being called by Puppet directly. So to extract the same stuff, I would have to either template the Ruby script, or pull the Duplicity script execution out of it. Templating the Ruby script wouldn't be terrible, but it also does not seem particularly necessary given that we don't use Mumble anymore.

REP-5871 Extracted Duplicity target name to variable

---

myModules/repose_jenkins/manifests/init.pp
myModules/repose_jenkins/manifests/legacy_slave.pp
myModules/repose_jenkins/manifests/master.pp
myModules/repose_jenkins/manifests/slave.pp

A couple of things to note here:
1. I modified our slave manifests to always install Java 8. As of [Jenkins 2.54](https://jenkins.io/changelog/#v2.54) the master and all slaves require Java 8.
* Maven template jobs created from the Maven plugin require the same version of Java as the Jenkins master to support some advanced integrations. To get around that, I converted our Maven jobs into Freestyle jobs and use Jenkin's JDK Tool Configuration to use Java 7 for those jobs.
1. I did not upgrade the Environment Injector Plugin (2.1.3 -> 2.1.5) as doing so introduces regressions without really buying us anything.

REP-6273 Upgrade Jenkins to 2.73.2

---

myModules/repose_jenkins/manifests/master.pp

The EnvInject API (envinject-api) and Environment Injector (envinject) plugins were not updated due to the two reported regression compatibility issues in 2.1.4.

REP-6488 Upgrade Jenkins version and Plugins

---

myModules/repose_jenkins/manifests/master.pp

This reverts commit 1660ce1cd4072ffd0d37b9765bfbdf139a6091cd.
This requires https://github.com/rackerlabs/repose/pull/1927 to already be merged.

REP-6900 Revert "Downgrading Jacoco plugin to known working version"

---

myModules/repose_influxdb/manifests/init.pp

See also:
https://github.com/rackerlabs/repose/pull/1939

REP-6980 Tagging Performance Test Metrics with Repose Version

---

myModules/repose_grafana/manifests/init.pp

Looks like it was just a security update, and so, a minor version bump for us.
Release notes:
https://community.grafana.com/t/release-notes-v-5-1-x/6958

Updated Grafana from v5.1.3 to v5.1.4

---

myModules/repose_grafana/manifests/init.pp

Release notes:
https://github.com/grafana/grafana/releases/tag/v5.2.1

REP-7100 Upgraded Grafana from v5.2.0 to v5.2.1

---

myModules/puppet_master/manifests/init.pp

The value was lowered from 90 days down to 60 in order to prevent disk space notifications from Nagios.

Updated the number of days Puppet Master reports are kept.

---

myModules/repose_grafana/manifests/init.pp

Release notes can be found at:
"Community" release notes can be found at:
https://community.grafana.com/t/release-notes-v5-3-x/10244

Upgraded Grafana from v5.2.4 to v5.3.0

---

myModules/repose_grafana/manifests/init.pp

Release notes can be found at:

Upgraded Grafana from v5.3.2 to v5.3.4

---

myModules/repose_grafana/manifests/init.pp

Release notes can be found at:

Upgraded Grafana from v5.4.0 to v5.4.1

---

myModules/repose_grafana/manifests/init.pp

Release notes can be found at:

Upgraded Grafana from v5.4.1 to v5.4.2

---

myModules/repose_jenkins/files/docker/daemon.json
myModules/repose_jenkins/manifests/build_slave.pp

Update docker to use devicemapper storage-driver to fix docker build error when building images under debian.

Fix docker error cpio: cap_set_file failed - Operation not supported
